export const createState = () => ({
    scene: 'corridor',
    flags: {
        keyState: 'hidden',
        cabinetOpen: false,
        laptopOn: false,
        laptopExpanded: false,
    },
    items: {
        key: 'corridor',
        note: 'corridor',
        laptop: 'room',
        crowbar: 'room',
        flash: 'room',
    },
    inventory: [],
    os: {
        windows: [],
        hung: [],
        history: [],
        cipher: {},
        khaos: 'idle',
        khaosProcess: false,
        user: null,
        keys: {},
        started: false,
        spied: { camera: false, location: false },
        apps: {},
        deleted: [],
    },
});
