export const createState = () => ({
    scene: 'corridor',
    flags: {
        keyState: 'hidden',
        doorUnlocked: false,
        cabinetOpen: false,
        laptopPlaced: false,
        crowbarOut: false,
        floorOpen: false,
        flashTaken: false,
        flashInserted: false,
        laptopOn: false,
        laptopExpanded: false,
        spiedCamera: false,
        spiedLocation: false,
    },
    items: {
        key: 'corridor',
        note: 'corridor',
        laptop: 'room',
        crowbar: 'room',
        flash: 'room',
    },
    inventory: [],
    held: null,
    open: null,
    os: {
        windows: [],
        hung: [],
        history: [],
        cipher: {},
        khaos: 'idle',
        khaosProcess: false,
        user: null,
        keys: {},
        started: false,
        usage: {},
        apps: {},
        deleted: [],
        trash: [],
    },
});
