export const biosLines = [
    { text: 'AMIBIOS(C)2003 American Megatrends, Inc.', wait: 80 },
    { text: 'BIOS Date: 08/14/03 15:22:41 Ver: 08.00.09', wait: 60 },
    { text: 'CPU : Intel(R) Pentium(R) M processor 1.60GHz', wait: 60 },
    { text: ' Speed : 1.60 GHz', wait: 320 },
    { text: '', wait: 0 },
    { text: 'Press DEL to run Setup', wait: 40 },
    { text: 'Press F11 for BBS POPUP', wait: 260 },
    { text: 'Checking NVRAM..', wait: 520 },
    { count: 512, text: 'MB OK', wait: 180 },
    { text: 'USB Device(s): 1 Keyboard, 1 Mouse', wait: 240 },
    { text: 'Auto-Detecting Pri Master..IDE Hard Disk', wait: 560 },
    { text: 'Auto-Detecting Sec Master..ATAPI CDROM', wait: 480 },
    { text: 'Pri Master: ST94011A 3.04', wait: 60 },
    { text: ' Ultra DMA Mode-5, S.M.A.R.T. Capable and Status OK', wait: 60 },
    { text: 'Sec Master: MATSHITADVD-RAM UJ-820S 1.02', wait: 380 },
    { text: 'Auto-detecting USB Mass Storage Devices ..', wait: 620 },
    { text: '01 USB mass storage devices found and configured.', wait: 300, when: ({ flashInserted }) => flashInserted },
    { text: '00 USB mass storage devices found and configured.', wait: 300, when: ({ flashInserted }) => !flashInserted },
    { text: '', wait: 0 },
    { text: 'Booting from Hard Disk...', wait: 900 },
];
